name: Löve Potion

on: [push]

jobs:
  first:
    name: 3DS
    container: docker://devkitpro/devkitarm
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make 3ds
