name: Löve Potion

on: [push]

jobs:
  first:
    name: 3DS
    runs-on: ubuntu-latest
    
    steps:
      - name: Docker Image
        uses: docker://devkitpro/devkitarm/latest
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make 3ds
