name: Löve Potion

on: [push]

jobs:
  first:
    name: 3DS
    container: 
      image: docker://devkitpro/devkitarm
      options: --cpus 2
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make 3ds
